#ifndef _JPEG_H_
#define _JPEG_H_

#if (CFG_SOC_NAME == SOC_BK7252N)
#define JPEG_BASE                       (0x00A03000)

#define JPEG_REG0X0_DEV_ID_ADDR         (JPEG_BASE + 0*4)
#define JPEG_REG0X1_VER_ID_ADDR         (JPEG_BASE + 1*4)

#define JPEG_REG0X2_CLK_CTRL_ADDR       (JPEG_BASE + 2*4)
#define JPEG_SOFT_RESET                 (1 << 0)
#define JPEG_CLK_GATE                   (1 << 1)

#define JPEG_REG0X3_GLOBAL_STA_SDDR     (JPEG_BASE + 3*4)

#define JPEG_REG0X4_ADDR                (JPEG_BASE + 4*4)
#define JPEG_EOF_OFFSET_POSI            (16)
#define JPEG_EOF_OFFSET_MASK            (0xFFFF)

#define JPEG_REG0X5_RXFIFO_DATA_ADDR    (JPEG_BASE + 5*4)

#define JPEG_REG0X6_ADDR                (JPEG_BASE + 6*4)
#define JPEG_INT_STATUS_POSI            (0)
#define JPEG_INT_STATUS_MASK            (0x2F)
#define JPEG_FIFO_RD_FINISH             (1 << 6)
#define JPEG_INT_SOF_BIT                (1 << 0)
#define JPEG_INT_EOF_BIT                (1 << 1)
#define JPEG_INT_HEAD_BIT               (1 << 2)
#define JPEG_INT_ERR_BIT                (1 << 3)
#define JPEG_INT_LINEC_BIT              (1 << 5)

#define JPEG_REG0X7_BYTE_CNT_PFRM_ADDR  (JPEG_BASE + 7*4)

#define JPEG_REG0X8_ADDR                (JPEG_BASE + 8*4)
#define JPEG_STREAM_FIFO_EMPTY          (1 << 26)
#define JPEG_STREAM_FIFO_FULL           (1 << 27)
#define JPEG_IS_DATA_SET                (1 << 28)

#define JPEG_REG0X9_ADDR                (JPEG_BASE + 9*4)
#define JPEG_Y_COUNT_POSI               (24)
#define JPEG_Y_COUNT_MASK               (0xFF)

#define JPEG_REG0XA_BYTE_CNT_LINE_ADDR  (JPEG_BASE + 10*4)

#define JPEG_REG0XC_ADDR                (JPEG_BASE + 12*4)
#define JPEG_ERR_INT_EN                 (1 << 0)
#define JPEG_HEAD_INT_EN                (1 << 1)
#define JPEG_SOF_INT_EN                 (1 << 2)
#define JPEG_EOF_INT_EN                 (1 << 3)
#define JPEG_MCLK_DIV_POSI              (4)
#define JPEG_MCLK_DIV_MASK              (0x3)
#define JPEG_LCLEAR_DIR                 (1 << 7)

#define JPEG_REG0XD_ADDR                (JPEG_BASE + 13*4)
#define JPEG_VCK_EDGE                   (1 << 0)
#define JPEG_VIDEO__BYTE_REV            (1 << 1)
#define JPEG_YUV_FMT_SEL_POSI           (2)
#define JPEG_YUV_FMT_SEL_MASK           (0x3)
#define JPEG_JPEG_ENC_EN                (1 << 4)
#define JPEG_JPEG_WORD_REVERSE          (1 << 5)
#define JPEG_ONLY_Y                     (1 << 6)
#define JPEG_YUVBUF_MODE                (1 << 7)
#define JPEG_X_PIXEL_POSI               (8)
#define JPEG_X_PIXEL_MASK               (0xFF)
#define JPEG_JPEG_ENC_SIZE              (1 << 16)
#define JPEG_BITRATE_CTRL               (1 << 17)
#define JPEG_BITRATE_STEP_POSI          (18)
#define JPEG_BITRATE_STEP_MASK          (0x3)
#define JPEG_AUTO_STEP                  (1 << 20)
#define JPEG_HSYNC_REV                  (1 << 21)
#define JPEG_VSYNC_REV                  (1 << 22)
#define JPEG_BITRATE_MODE               (1 << 23)
#define JPEG_Y_PIXEL_POSI               (24)
#define JPEG_Y_PIXEL_MASK               (0xFF)

#define JPEG_REG0XE_TARGET_BYTE_H_ADDR  (JPEG_BASE + 14*4)
#define TARGET_BYTE_H_MASK              (0xFFFFFFFF)
#define JPEG_REG0XF_TARGET_BYTE_L_ADDR  (JPEG_BASE + 15*4)
#define TARGET_BYTE_L_MASK              (0xFFFFFFFF)

#define JPEG_REG20_QUANT_TAB            (JPEG_BASE + 0x20 * 4)
#define JPEG_QUANT_TAB_LEN              (32)
#define JPEG_REG0X20_QUTABLE_0_ADDR     (JPEG_BASE + 32*4)
#define JPEG_REG0X21_QUTABLE_1_ADDR     (JPEG_BASE + 33*4)
#define JPEG_REG0X22_QUTABLE_2_ADDR     (JPEG_BASE + 34*4)
#define JPEG_REG0X23_QUTABLE_3_ADDR     (JPEG_BASE + 35*4)
#define JPEG_REG0X24_QUTABLE_4_ADDR     (JPEG_BASE + 36*4)
#define JPEG_REG0X25_QUTABLE_5_ADDR     (JPEG_BASE + 37*4)
#define JPEG_REG0X26_QUTABLE_6_ADDR     (JPEG_BASE + 38*4)
#define JPEG_REG0X27_QUTABLE_7_ADDR     (JPEG_BASE + 39*4)
#define JPEG_REG0X28_QUTABLE_8_ADDR     (JPEG_BASE + 40*4)
#define JPEG_REG0X29_QUTABLE_9_ADDR     (JPEG_BASE + 41*4)
#define JPEG_REG0X2A_QUTABLE_A_ADDR     (JPEG_BASE + 42*4)
#define JPEG_REG0X2B_QUTABLE_B_ADDR     (JPEG_BASE + 43*4)
#define JPEG_REG0X2C_QUTABLE_C_ADDR     (JPEG_BASE + 44*4)
#define JPEG_REG0X2D_QUTABLE_D_ADDR     (JPEG_BASE + 45*4)
#define JPEG_REG0X2E_QUTABLE_E_ADDR     (JPEG_BASE + 46*4)
#define JPEG_REG0X2F_QUTABLE_F_ADDR     (JPEG_BASE + 47*4)
#define JPEG_REG0X30_QUTABLE_10_ADDR    (JPEG_BASE + 48*4)
#define JPEG_REG0X31_QUTABLE_11_ADDR    (JPEG_BASE + 49*4)
#define JPEG_REG0X32_QUTABLE_12_ADDR    (JPEG_BASE + 50*4)
#define JPEG_REG0X33_QUTABLE_13_ADDR    (JPEG_BASE + 51*4)
#define JPEG_REG0X34_QUTABLE_14_ADDR    (JPEG_BASE + 52*4)
#define JPEG_REG0X35_QUTABLE_15_ADDR    (JPEG_BASE + 53*4)
#define JPEG_REG0X36_QUTABLE_16_ADDR    (JPEG_BASE + 54*4)
#define JPEG_REG0X37_QUTABLE_17_ADDR    (JPEG_BASE + 55*4)
#define JPEG_REG0X38_QUTABLE_18_ADDR    (JPEG_BASE + 56*4)
#define JPEG_REG0X39_QUTABLE_19_ADDR    (JPEG_BASE + 57*4)
#define JPEG_REG0X3A_QUTABLE_1A_ADDR    (JPEG_BASE + 58*4)
#define JPEG_REG0X3B_QUTABLE_1B_ADDR    (JPEG_BASE + 59*4)
#define JPEG_REG0X3C_QUTABLE_1C_ADDR    (JPEG_BASE + 60*4)
#define JPEG_REG0X3D_QUTABLE_1D_ADDR    (JPEG_BASE + 61*4)
#define JPEG_REG0X3E_QUTABLE_1E_ADDR    (JPEG_BASE + 62*4)
#define JPEG_REG0X3F_QUTABLE_1F_ADDR    (JPEG_BASE + 63*4)


#endif

#endif // _JPEG_H_
